[package]
name = "Hacker-Term"
version = "0.6.0"
edition = "2021"
description = "Hacker Term — Slint-powered beautiful terminal, works on ALL GPUs for HackerOS"

[dependencies]
slint = { version = "1.5", default-features = false, features = [
    "backend-winit",
    "renderer-winit-software",
    "renderer-winit-femtovg",
    "std",
    "compat-1-2",
] }
fontdue = "0.8"
portable-pty = "0.8"
bitflags = "2"
anyhow = "1"
log = "0.4"
env_logger = "0.11"
unicode-width = "0.1"
hk-parser = "0.2.1"
arboard = "3.2"
image = "0.24"
lazy_static = "1.4"
regex = "1.10"
ctrlc = "3.4"
indexmap = "2.0"
dirs = "5.0"                     # dodana

[build-dependencies]
slint-build = "1.5"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true
