import { TerminalTheme, Translations } from './types';

export const THEMES: Record<string, TerminalTheme> = {
    'Hacker (Default)': {
        name: 'Hacker',
        background: '#00000000', // Handled by App container opacity
        foreground: '#CDD6F4',
            cursor: '#CBA6F7',
            selection: 'rgba(203, 166, 247, 0.3)',
            black: '#45475A',
            red: '#F38BA8',
            green: '#A6E3A1',
            yellow: '#F9E2AF',
            blue: '#89B4FA',
            magenta: '#F5C2E7',
            cyan: '#94E2D5',
            white: '#BAC2DE',
            brightBlack: '#585B70',
            brightRed: '#F38BA8',
            brightGreen: '#A6E3A1',
            brightYellow: '#F9E2AF',
            brightBlue: '#89B4FA',
            brightMagenta: '#F5C2E7',
            brightCyan: '#94E2D5',
            brightWhite: '#A6ADC8'
    },
    'Cyberpunk': {
        name: 'Cyberpunk',
        background: '#00000000',
        foreground: '#00ff9f',
            cursor: '#ff003c',
            selection: 'rgba(255, 0, 60, 0.3)',
            black: '#100b20',
            red: '#ff003c',
            green: '#00ff9f',
            yellow: '#fcee0a',
            blue: '#00b8ff',
            magenta: '#d600ff',
            cyan: '#00fff5',
            white: '#ffffff',
            brightBlack: '#45475a',
            brightRed: '#ff4d76',
            brightGreen: '#50fa7b',
            brightYellow: '#ffffa5',
            brightBlue: '#8be9fd',
            brightMagenta: '#ff79c6',
            brightCyan: '#8be9fd',
            brightWhite: '#ffffff'
    },
    'Dracula': {
        name: 'Dracula',
        background: '#00000000',
        foreground: '#f8f8f2',
            cursor: '#bd93f9',
            selection: '#44475a',
            black: '#21222c',
            red: '#ff5555',
            green: '#50fa7b',
            yellow: '#f1fa8c',
            blue: '#bd93f9',
            magenta: '#ff79c6',
            cyan: '#8be9fd',
            white: '#f8f8f2',
            brightBlack: '#6272a4',
            brightRed: '#ff6e6e',
            brightGreen: '#69ff94',
            brightYellow: '#ffffa5',
            brightBlue: '#d6acff',
            brightMagenta: '#ff92df',
            brightCyan: '#a4ffff',
            brightWhite: '#ffffff'
    }
};

export const TRANSLATIONS: Record<string, Translations> = {
    pl: {
        settings: 'Ustawienia',
        appearance: 'Wygląd',
        terminal: 'Terminal',
        about: 'O programie',
        language: 'Język',
        shell: 'Powłoka',
        theme: 'Motyw Kolorystyczny',
        fontSize: 'Rozmiar czcionki',
        opacity: 'Przezroczystość',
        blur: 'Rozmycie tła',
        padding: 'Marginesy',
        cursorStyle: 'Styl kursora',
        cursorBlink: 'Mruganie kursora',
        fontFamily: 'Rodzina czcionek',
        close: 'Zamknij',
        newTab: 'Nowa karta',
        ready: 'Gotowy'
    },
    en: {
        settings: 'Settings',
        appearance: 'Appearance',
        terminal: 'Terminal',
        about: 'About',
        language: 'Language',
        shell: 'Shell',
        theme: 'Color Theme',
        fontSize: 'Font Size',
        opacity: 'Window Opacity',
        blur: 'Background Blur',
        padding: 'Terminal Padding',
        cursorStyle: 'Cursor Style',
        cursorBlink: 'Cursor Blink',
        fontFamily: 'Font Family',
        close: 'Close',
        newTab: 'New Tab',
        ready: 'Ready'
    }
};
